# general settings
name: 230125_EDVR_M_RR_lr_1e-4_woPD_wpre3Dconv
model_type: EDVRModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS_RR
    type: REDSDataset
    dataroot_gt: datasets/REDS/train_GT
    dataroot_lq: datasets/REDS/train_RR
    dataroot_flow: ~
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_RR_GT.txt
    val_partition: official  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3 #change from 3
    batch_size_per_gpu: 2 #change from 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoTestDataset
    dataroot_gt: datasets/REDS/validation_GT
    dataroot_lq: datasets/REDS/validation_RR
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_RR_val_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 5
    padding: reflection_circle

# network structures
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 10
  center_frame_idx: ~
  hr_in: true
  with_predeblur: false
  with_pre3Dconv: true
  with_3Dconv: false
  with_pcd: true
  with_aligned_3Dconv: false
  with_tsa: true
# path
path:
  pretrain_network_g: ~
  #pretrain_network_g: experiments\221218_EDVR_M_RR_REDS_600k_B4G8_valREDS4_lr_1e-4_wPCD_dbg\models\net_g_40000.pth
  strict_load_g: true
  resume_state: ~
  #resume_state: experiments\221218_EDVR_M_RR_REDS_600k_B4G8_valREDS4_lr_1e-4_wPCD_dbg\training_states\40000.state
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000, 100000, 150000, 300000, 1400000] # change from [50000, 100000, 150000, 150000, 150000]
    restart_weights: [1, 1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 2000000
  warmup_iter: -1  # no warm up
  tsa_iter: 50000
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
